# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/blenderproc-test-scenes',
                'doc_host': 'https://flupppi.github.io',
                'git_url': 'https://github.com/flupppi/blenderproc-test-scenes',
                'lib_path': 'blenderproc_test_scenes'},
  'syms': { 'blenderproc_test_scenes.core': { 'blenderproc_test_scenes.core.compute_group_regularity': ( 'sketching_gestalt_space.html#compute_group_regularity',
                                                                                                         'blenderproc_test_scenes/core.py'),
                                              'blenderproc_test_scenes.core.create_group_aabb': ( 'sketching_gestalt_space.html#create_group_aabb',
                                                                                                  'blenderproc_test_scenes/core.py'),
                                              'blenderproc_test_scenes.core.generate_cube_grid': ( 'sketching_gestalt_space.html#generate_cube_grid',
                                                                                                   'blenderproc_test_scenes/core.py'),
                                              'blenderproc_test_scenes.core.generate_custom_scene': ( 'sketching_gestalt_space.html#generate_custom_scene',
                                                                                                      'blenderproc_test_scenes/core.py'),
                                              'blenderproc_test_scenes.core.group_by_proximity': ( 'sketching_gestalt_space.html#group_by_proximity',
                                                                                                   'blenderproc_test_scenes/core.py')}}}
